### ISSUE TITLE
Getting -40 

### ISSUE THREAD

**Issue by arifainchtein** [RobTillaart/CHT8305#15] opened 2024-09-16 10:18 UTC
Hello,
I am using an esp32 and a dfrobot 0546 sdensor that uses the CHT8305.  When i ran the Minimal Example i get -40 for temperature and 0 for humidity.  Any ideas as to why this is happening?  The Wire scanner does find a device in address x040 so its finding the sensor.

Any ideas?

thanks

**Comment by RobTillaart** [comment] 2024-09-16 10:24
Thanks for the question, 

I have no clue at the moment. As I am working on another project I will dive into this later today if time permits.

**Comment by RobTillaart** [comment] 2024-09-16 11:04
Analysis
In the CHT8305.cpp there is the read with this code

```c
  uint16_t tmp = data[0] << 8 | data[1];
  _temperature = tmp * (165.0 / 65535.0) - 40.0;
   tmp = data[2] << 8 | data[3];
  _humidity    = tmp * (1.0 / 655.35);  //  == / 65535 * 100%
````

if all data[] read == 0 you get the hum = 0 and temp = -40.

looking further.

**Comment by RobTillaart** [comment] 2024-09-16 11:06
```c
int CHT8305::_readRegister(uint8_t reg, uint8_t * buf, uint8_t size)
{
  _wire->beginTransmission(_address);
  _wire->write(reg);
  int n = _wire->endTransmission();
  if (n != 0) return CHT8305_ERROR_I2C;

  if (reg == CHT8305_REG_TEMPERATURE)  //  wait for conversion...
  {
    delay(_conversionDelay);  //  2x 6.5 ms @ 14 bit = 14  (10 works).
  }

  n = _wire->requestFrom(_address, size);
  if (n == size)
  {
    for (uint8_t i = 0; i < size; i++)
    {
      buf[i] = _wire->read();
    }
  }
  return CHT8305_OK;
}
```
if low level read got an I2C error, the data will not be filled.

==>so need to implement better error handling.

**Comment by RobTillaart** [comment] 2024-09-16 11:07
Added bug  label as this should be fixed.

**Comment by RobTillaart** [comment] 2024-09-16 11:10
Can you run **CHT8305_status.ino** and post a dozen lines of its output?

**Comment by RobTillaart** [comment] 2024-09-16 11:36
Created a develop branch with a new function **getLastError()**.
this patch captures current errors in a variable which is accessible via **getLastError()**

More code is needed to catch all errors but this is a start.

Can you test this branch? 
You can adjust the minimal sketch to print the last Error after reading the sesnor.

Thanks, back to my own project

**Comment by RobTillaart** [comment] 2024-09-16 13:54
@arifainchtein 

> Any ideas?

Do you have pull up resistors on the SDA/SCL lines?
Long wires?

**Comment by arifainchtein** [comment] 2024-09-16 20:35
Hi Robert,I am in Australia and just got your messages.  I do have the i2c lines pull up with a 10k resistors.  The length of the cable is about 50cm.i will use the development branch you created to test.  i will also connect the sensor directly to the board and test to eliminate  that variable.will report later on todaythanks againSent from my iPhoneOn 16 Sep 2024, at 23:54, Rob Tillaart ***@***.***> wrote:﻿
@arifainchtein

Any ideas?

Do you have pull up resistors on the SDA/SCL lines?
Long wires?

**Comment by RobTillaart** [comment] 2024-09-19 17:43
> I do have the i2c lines pull up with a 10k resistors.  The length of the cable is about 50cm

Should be OK, especially the device sees its address (_"The Wire scanner does find a device"_)

@arifainchtein 

just thinking what could cause the failure:
- Are there more devices on the I2c/Wire bus? If those also have the address 0x40 ?
- The AD0 pin is connected to GND and not floating?
- Have you tried another address e.g. VCC to AD0 to get 0x41?

**Comment by RobTillaart** [comment] 2024-09-20 15:06
@arifainchtein 
I have tested her with an CHT8305 sensor and cannot reproduce the error you have.
Please give the develop branch a try and add ```Serial.println(cht.getLastError());``` where appropriate.
Might give a clue why it fails.

**Comment by RobTillaart** [comment] 2024-09-21 10:24
@arifainchtein 

> will report later on today

Did you test your project with the latest develop branch already?
Anything to report?

**Comment by arifainchtein** [comment] 2024-09-21 21:22
hi Robert,weird i sent you a message a few days ago  but somehow it did not get to you. Yes, your develop branch worked perfect.  i even berified that it was your code because i used the dfrobot example (the sensor is dfrobot) and it did not work, but when i used your develop branch it works perfect. send me an mail to confirm that you received this one.thanks a lot for your time, really appreciated.Sent from my iPhoneOn 21 Sep 2024, at 20:24, Rob Tillaart ***@***.***> wrote:﻿
@arifainchtein

will report later on today

Did you test your project with the latest develop branch already?
Anything to report?

**Comment by RobTillaart** [comment] 2024-09-21 21:32
Thanks for the update, I got this message.
Given that the code works, I will merge the develop branch asap.

Thanks again for the feedback

**Comment by RobTillaart** [comment] 2024-09-22 09:41
Merged develop branch into master,
Again, thank you for reporting the issue

**Closed as completed** 2024-09-22 09:40 UTC
Labels: bug, question
